## Стек Docker Compose для запуска Selenoid, Selenoid UI и тестов
services:
  selenoid:
    # Основной хаб Selenoid (динамически запускает контейнеры с браузерами)
    image: aerokube/selenoid:latest-release
    # Принудительно amd64: официальные образы Selenoid собраны под amd64; на Apple Silicon используется эмуляция
    platform: linux/amd64
    container_name: selenoid
    # Аргументы запуска Selenoid (список, чтобы избежать проблем парсинга)
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video",
      "-log-output-dir", "/opt/selenoid/logs",
      "-capture-driver-logs",
      "-service-startup-timeout", "2m",
      "-container-network", "selenoid_grid"
    ]
    ports:
      # Публикуем порт Selenoid hub
      - "4444:4444"
    volumes:
      # Доступ к Docker сокету для управления контейнерами браузеров
      - /var/run/docker.sock:/var/run/docker.sock
      # Подключаем конфигурацию браузеров
      - ./selenoid/browsers.json:/etc/selenoid/browsers.json:ro
      # Пробрасываем каталоги видео и логов на хост
      - ./selenoid/video:/opt/selenoid/video
      - ./selenoid/logs:/opt/selenoid/logs
    environment:
      # Важно для macOS: путь к видео должен быть расшарен в Docker Desktop
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/sergeytsarev/selenium-selenoid-demo/selenoid/video
    networks:
      - grid
    healthcheck:
      # Проверяем, что Selenoid отвечает на /status (wget доступен в образе)
      test: ["CMD-SHELL", "wget -qO- http://localhost:4444/status >/dev/null || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 60
      start_period: 5s

  selenoid-ui:
    # Веб‑интерфейс для наблюдения за сессиями, скачивания видео и просмотра логов
    image: aerokube/selenoid-ui:latest-release
    platform: linux/amd64
    container_name: selenoid-ui
    depends_on:
      - selenoid
    ports:
      # Публикуем UI
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - grid

  tests:
    # Контейнер тест‑раннера с pytest + selenium
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      # Подключение к Selenoid по DNS‑имени внутри сети compose
      - SELENOID_URL=http://selenoid:4444/wd/hub
      # Имя используется для удобного имени видеофайла
      - TEST_NAME=test_google
    volumes:
      # Монтируем проект для запуска исходников без пересборки образа
      - ./:/app:rw
    working_dir: /app
    # Ждать готовности Selenoid через healthcheck
    depends_on:
      selenoid:
        condition: service_healthy
    # Используем CMD из Dockerfile.tests (pytest -q)
    networks:
      - grid

volumes: {}

## Общая пользовательская сеть для предсказуемого DNS и связи
networks:
  grid:
    name: selenoid_grid


